package com.dsu.accoutingdsu.entity;
// Generated Aug 23, 2017 1:12:31 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Payroll generated by hbm2java
 */
@Entity
@Table(name="payroll"
    ,catalog="organization"
)
public class Payroll  implements java.io.Serializable {


     private int tabelId;
     private ReportCard reportCard;
     private Integer payroll;
     private Date dateOfPayroll;

    public Payroll() {
    }

	
    public Payroll(ReportCard reportCard, Date dateOfPayroll) {
        this.reportCard = reportCard;
        this.dateOfPayroll = dateOfPayroll;
    }
    public Payroll(ReportCard reportCard, Integer payroll, Date dateOfPayroll) {
       this.reportCard = reportCard;
       this.payroll = payroll;
       this.dateOfPayroll = dateOfPayroll;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="reportCard"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="tabel_id", unique=true, nullable=false)
    public int getTabelId() {
        return this.tabelId;
    }
    
    public void setTabelId(int tabelId) {
        this.tabelId = tabelId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public ReportCard getReportCard() {
        return this.reportCard;
    }
    
    public void setReportCard(ReportCard reportCard) {
        this.reportCard = reportCard;
    }

    
    @Column(name="payroll")
    public Integer getPayroll() {
        return this.payroll;
    }
    
    public void setPayroll(Integer payroll) {
        this.payroll = payroll;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_of_payroll", nullable=false, length=10)
    public Date getDateOfPayroll() {
        return this.dateOfPayroll;
    }
    
    public void setDateOfPayroll(Date dateOfPayroll) {
        this.dateOfPayroll = dateOfPayroll;
    }




}


