package com.dsu.accoutingdsu.entity;
// Generated Aug 23, 2017 1:12:31 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Post generated by hbm2java
 */
@Entity
@Table(name="post"
    ,catalog="organization"
    , uniqueConstraints = @UniqueConstraint(columnNames="post") 
)
public class Post  implements java.io.Serializable {


     private Integer postId;
     private String post;
     private BigDecimal salary;
     private Set userProfiles = new HashSet(0);

    public Post() {
    }

    public Post(String post, BigDecimal salary, Set userProfiles) {
       this.post = post;
       this.salary = salary;
       this.userProfiles = userProfiles;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="post_id", unique=true, nullable=false)
    public Integer getPostId() {
        return this.postId;
    }
    
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    
    @Column(name="post", unique=true)
    public String getPost() {
        return this.post;
    }
    
    public void setPost(String post) {
        this.post = post;
    }

    
    @Column(name="salary", precision=10)
    public BigDecimal getSalary() {
        return this.salary;
    }
    
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="post")
    public Set getUserProfiles() {
        return this.userProfiles;
    }
    
    public void setUserProfiles(Set userProfiles) {
        this.userProfiles = userProfiles;
    }




}


