package com.dsu.accoutingdsu.entity;
// Generated Aug 23, 2017 1:12:31 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * ReportCard generated by hbm2java
 */
@Entity
@Table(name="report_card"
    ,catalog="organization"
)
public class ReportCard  implements java.io.Serializable {


     private Integer tabelId;
     private UserProfile userProfile;
     private Integer timeWorked;
     private Integer timeSickness;
     private Integer vacation;
     private Payroll payroll;

    public ReportCard() {
    }

	
    public ReportCard(UserProfile userProfile) {
        this.userProfile = userProfile;
    }
    public ReportCard(UserProfile userProfile, Integer timeWorked, Integer timeSickness, Integer vacation, Payroll payroll) {
       this.userProfile = userProfile;
       this.timeWorked = timeWorked;
       this.timeSickness = timeSickness;
       this.vacation = vacation;
       this.payroll = payroll;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="tabel_id", unique=true, nullable=false)
    public Integer getTabelId() {
        return this.tabelId;
    }
    
    public void setTabelId(Integer tabelId) {
        this.tabelId = tabelId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="person_id", nullable=false)
    public UserProfile getUserProfile() {
        return this.userProfile;
    }
    
    public void setUserProfile(UserProfile userProfile) {
        this.userProfile = userProfile;
    }

    
    @Column(name="time_worked")
    public Integer getTimeWorked() {
        return this.timeWorked;
    }
    
    public void setTimeWorked(Integer timeWorked) {
        this.timeWorked = timeWorked;
    }

    
    @Column(name="time_sickness")
    public Integer getTimeSickness() {
        return this.timeSickness;
    }
    
    public void setTimeSickness(Integer timeSickness) {
        this.timeSickness = timeSickness;
    }

    
    @Column(name="vacation")
    public Integer getVacation() {
        return this.vacation;
    }
    
    public void setVacation(Integer vacation) {
        this.vacation = vacation;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="reportCard")
    public Payroll getPayroll() {
        return this.payroll;
    }
    
    public void setPayroll(Payroll payroll) {
        this.payroll = payroll;
    }




}


