package com.dsu.accoutingdsu.entity;
// Generated Aug 23, 2017 1:12:31 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * WorkCategory generated by hbm2java
 */
@Entity
@Table(name="work_category"
    ,catalog="organization"
)
public class WorkCategory  implements java.io.Serializable {


     private Integer categoryId;
     private String category;
     private BigDecimal ratio;
     private Set userProfiles = new HashSet(0);

    public WorkCategory() {
    }

    public WorkCategory(String category, BigDecimal ratio, Set userProfiles) {
       this.category = category;
       this.ratio = ratio;
       this.userProfiles = userProfiles;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="category_id", unique=true, nullable=false)
    public Integer getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    
    @Column(name="category")
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

    
    @Column(name="ratio", precision=10)
    public BigDecimal getRatio() {
        return this.ratio;
    }
    
    public void setRatio(BigDecimal ratio) {
        this.ratio = ratio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="workCategory")
    public Set getUserProfiles() {
        return this.userProfiles;
    }
    
    public void setUserProfiles(Set userProfiles) {
        this.userProfiles = userProfiles;
    }




}


